### ISSUE TITLE
Интеграция с jQuery не работает. 

### ISSUE THREAD

**Issue by shalomov** [andreyalexeich/gulp-scss-starter#109]
Добрый день. Подключение jQuery всё ещё не работает в сборке, прошу протестировать совместимость.

**Comment by nikolays93** [comment]
Пробовали ```Import $ from "jquery"```?

**Comment by shalomov** [comment]
Если я правильно понял тут все импорты уже прописаны :
    plugins: [ 
        new webpack.ProvidePlugin({ 
            "jQuery": "jquery", 
            "window.jQuery": "jquery", 
            "jquery": "jquery", 
            "window.jquery": "jquery", 
            "$": "jquery", 
            "window.$": "jquery" 
        }) 
    ],

Дело в том, что у меня нет никаких ошибок, после npm i jquery я подключаю файлы с кодом на jquery и на этом всё. Не дебажатся даже js-ники, просто выполнение сценариев в браузере останавливается.

**Comment by andreyalexeich** [comment]
@shalomov некоторые плагины нужно подключать с полным путём от папки ```node_modules```
