### ISSUE TITLE
Проблема с отслеживанием файлов

### ISSUE THREAD

**Issue by zapaza** [andreyalexeich/gulp-scss-starter#119]
Последнее время по какой-то причине перестает работать вотчер, ошибок в консоле нет, просто при изменении файлов не отрабатывает сборщик, и проект не перебирается, может знает кто в чем может быть причина?

**Comment by andreyalexeich** [comment]
@zapaza привет, причина точно неизвестна. Может надо отдельно обновить gulp, если обновление выходило

**Comment by zapaza** [comment]
> @zapaza привет, причина точно неизвестна. Может надо отдельно обновить gulp, если обновление выходило

gulp стоит версии 4.0.2

**Comment by zapaza** [comment]
если это тольку у меня проблема и возможно связана с по, то есть другой вопрос, что в таске на сбор css нужно поменять, что бы сборщик не вылетал, если какое-то свойство не так написал

**Comment by andreyalexeich** [comment]
менять не нужно ничего, у остальных работает. Но поищи в любом случае на всякий, pr отправишь

**Comment by zapaza** [comment]
Окей, спасибо

**Comment by Air-Sidney** [comment]
редко, но тоже возникает данная проблема
