### ISSUE TITLE
На Ubuntu возникает ошибка "SyntaxError: Cannot use import statement outside a module ..."

### ISSUE THREAD

**Issue by sashakobzeww** [andreyalexeich/gulp-scss-starter#121]
Здравствуйте.

Пользуюсь уже на нескольких проектах Вашей сборкой. За что Вам спасибо!

С недавних пор решил осваивать Linux. И столкнулся с тем, что на Ubuntu сборка не запускается и выдаёт при запуске следующую ошибку:

```
    paranoic:~/PhpstormProjects/20_18$ gulp
    [14:27:25] Requiring external module @babel/register
    /home/paranoic/PhpstormProjects/project10/gulpfile.babel.js:3
    import gulp from "gulp";
    ^^^^^^
    
    SyntaxError: Cannot use import statement outside a module
```

Везде пишут, что это беды с babel. Но почему на одной ОС они есть, а не другой нету?

Уже предпринимал следующие меры, но они не сработали:

- На всякий случай проверил запускается какая-то другая сборка на Ubuntu. Есть сборка без import`ов - запускается

- Менял версию node на ту которая поддерживает модули и добавлял в package запись "type": "module"

Что нужно предпринять, чтобы сборка работала и на Ubuntu?

**Comment by andreyalexeich** [comment]
@sashakobzeww привет, попробуй:

```js 
// package.json
{
  "type": "module"
}```

**Comment by sashakobzeww** [comment]
Спасибо за ответ
Задача использования сборки на Linux исчезла
У других пользователей сборка работает
