### ISSUE TITLE
С 16 версией nodejs не работает.

### ISSUE THREAD

**Issue by rtxrulez** [andreyalexeich/gulp-scss-starter#122]
Выводится ошибка на этапе установки пакета **sharp**. Самостоятельно разобраться не смог.

**Comment by Zobakka** [comment]
Поставил nvm manager, экспериментальным образом выяснил, что работает до версии 13.14.0

**Comment by SeryiBaran** [comment]
Эта сборка не обновляется уже 2 года!

**Comment by Sellato** [comment]
> Поставил nvm manager, экспериментальным образом выяснил, что sharp работает до версии 13.14.0

Думаю не совсем так, судя по вот этой ошибке `error stylelint@14.1.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "14.0.0"`

работать будет на двух конкретных версиях 12.20.0 и 14.13.1 , что собственно подтверждено моим опытом. 

Работает на версиях `12.20.0 и 14.13.1`

**Comment by andreyalexeich** [comment]
Скоро всё обновлю, ошибки должны уйти. Если нет — пишите сюда :)

**Comment by SeryiBaran** [comment]
Огромное спасибо!

**Comment by andreyalexeich** [comment]
@SeryiBaran попробуй, как теперь ведёт себя сборка

**Comment by SeryiBaran** [comment]
> @SeryiBaran попробуй, как теперь ведёт себя сборка

Написал `yarn`;  
Написал `yarn dev`;  
Вылезло такое:

`yarn run v1.22.15`
`$ gulp`
`[13:06:21] Failed to load external module @babel/register`
`[13:06:21] Error: Cannot find module '@babel/register' from 'E:\mytemp\gulp-scss-starter-master'`
`[13:06:21] Failed to load external module babel-register`
`[13:06:21] Error: Cannot find module 'babel-register' from 'E:\mytemp\gulp-scss-starter-master'`
`[13:06:21] Failed to load external module babel-core/register`
`[13:06:21] Error: Cannot find module 'babel-core/register' from 'E:\mytemp\gulp-scss-starter-master'`
`[13:06:21] Failed to load external module babel/register`
`[13:06:21] Error: Cannot find module 'babel/register' from 'E:\mytemp\gulp-scss-starter-master'`
`[13:06:21] Local modules not found in E:\mytemp\gulp-scss-starter-master`
`[13:06:21] Try running: yarn install`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Вот полные логи:  
[logs.txt](https://github.com/andreyalexeich/gulp-scss-starter/files/8283706/logs.txt)

**Comment by andreyalexeich** [comment]
Меня смущает наименование папки, ты архивом качал? Нужно с ```git clone```

**Comment by kobzarliliia** [comment]
Появилась такая же ошибка как и у автора выше. Делала git clone. В чем может быть проблема?
![image](https://user-images.githubusercontent.com/91090875/159134200-b850b456-304a-484b-a629-656a1970490d.png)

**Comment by andreyalexeich** [comment]
@kobzarliliia случаем в логе чуть выше нет ошибки о inotify 1.4.6?

**Comment by kobzarliliia** [comment]
> @kobzarliliia случаем в логе чуть выше нет ошибки о inotify 1.4.6?

вот все логи
![image](https://user-images.githubusercontent.com/91090875/159134695-b8c3507c-a8fb-4222-856f-42527b7a2279.png)

**Comment by andreyalexeich** [comment]
> > @kobzarliliia случаем в логе чуть выше нет ошибки о inotify 1.4.6?
> 
> вот все логи ![image](https://user-images.githubusercontent.com/91090875/159134695-b8c3507c-a8fb-4222-856f-42527b7a2279.png)

удали папку ```.yarn```, затем введи в папке сборки ```yarn set version berry```  и попробуй ещё раз

**Comment by kobzarliliia** [comment]
> 

работает, спасибо

**Comment by andreyalexeich** [comment]
сервер запустился?

**Comment by kobzarliliia** [comment]
> сервер запустился?

да, запустился

**Comment by andreyalexeich** [comment]
> > сервер запустился?
> 
> да, запустился

отлично, я залил исправления. Спасибо :)
