### ISSUE TITLE
Существует проблема с babel-loader

### ISSUE THREAD

**Issue by lebuhorskiy** [andreyalexeich/gulp-scss-starter#123]
Я боролся несколько часов с тем что не мог подключить скрипты.
Точнее я их подключил, но они отказывались работать, браузер их просто не воспринимал.
Я убрал в webpack.config.js блок 
use: {...}
и все заработало!

**Comment by andreyalexeich** [comment]
@lebuhorskiy я этот блок добавлял, потому что без него не работал jQuery, точно не помню. Но если помогло — хорошо!
