### ISSUE TITLE
Предложение добавить watcher для настройки сетки smartgrid

### ISSUE THREAD

**Issue by Zobakka** [andreyalexeich/gulp-scss-starter#124]
Не очень удобно постоянно перезапускать сборку при добавлении или внесении изменений в настройки smartgrid.

Можно вынести все настройки в отдельный файл и добавить watcher для него, в результате чего файл примесей будет пересобираться по новым настройкам проекта.

Могу оформить, если идея покажется разумной.

**Comment by andreyalexeich** [comment]
Smartgrid удалил, так как после обновления Sass перестали поддерживаться некоторые фишки
