### ISSUE TITLE
Не описывается как использовать svg

### ISSUE THREAD

**Issue by mars092** [andreyalexeich/gulp-scss-starter#129]
Есть спрайты svg. Не могу найти пример как обратится к спрайту

**Comment by mars092** [comment]
Было бы хорошо описать в документации про svg use.

К примеру мы добавили svg `logo.svg` и обратится к нему нужно в таком виде:
```
<svg>
  <use xlink:href="img/sprites/sprite.svg#logo"></use>
</svg>
```
Что бы поменять цвет svg нужно в css обратится к нему в таком виде:
```
svg use {
  fill: red;
}
```
Но что бы это заработало в svg нужно почить некоторые параметры. К примеру в таком виде отдает svg figma:
```
<svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4.90918 4.04542L13.091 9.54088L4.90918 14.9545L4.90918 4.04542Z" fill="#1B1B1D"/>
</svg>
```
Нужно удалить эти кусочки `fill="none"` и `fill="#1B1B1D"`. Должно получится вот так:
```
<svg width="18" height="19" viewBox="0 0 18 19" xmlns="http://www.w3.org/2000/svg">
  <path d="M4.90918 4.04542L13.091 9.54088L4.90918 14.9545L4.90918 4.04542Z" />
</svg>
```

**Comment by andreyalexeich** [comment]
Сделано
