### ISSUE TITLE
Пожалуйста, подправьте readme

### ISSUE THREAD

**Issue by Sellato** [andreyalexeich/gulp-scss-starter#131]
Вместо `установите NodeJS 12-ой версии`

Укажите явно `установите NodeJS 12.20.0 или 14.13.1`

мой вывод сделан исходя из ошибки `error stylelint@14.1.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "14.0.0"
`

Это будет справедливо :)

**Comment by andreyalexeich** [comment]
@Sellato  скоро всё обновлю, должны ошибки уйти, тут stylelint старый
