### ISSUE TITLE
баг вылез, может подскажешь с чем связано. 2 раза переустанавливал

### ISSUE THREAD

**Issue by zagz16** [andreyalexeich/gulp-scss-starter#138]
Internal Error: gulp-scss-starter@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at tF.getCandidates (C:\Users\zagz\Desktop\тестовое 2\gulp-scss-starter\.yarn\releases\yarn-3.2.0.cjs:437:4480)
    at wd.getCandidates (C:\Users\zagz\Desktop\тестовое 2\gulp-scss-starter\.yarn\releases\yarn-3.2.0.cjs:395:1281)
    at C:\Users\zagz\Desktop\тестовое 2\gulp-scss-starter\.yarn\releases\yarn-3.2.0.cjs:441:7765
    at Pg (C:\Users\zagz\Desktop\тестовое 2\gulp-scss-starter\.yarn\releases\yarn-3.2.0.cjs:394:11098)
    at le (C:\Users\zagz\Desktop\тестовое 2\gulp-scss-starter\.yarn\releases\yarn-3.2.0.cjs:441:7745)
PS C:\Users\zagz\Desktop\тестовое 2\gulp-scss-starter>

**Comment by osvax** [comment]
Удали файл yarn.lock и запусти по новой yarn install

**Comment by zagz16** [comment]
@osvax  не помогло.
я даже удалял и заново все устанавливал.


если брать инструкцию даже, то зависимости это последнее, что в проекте загружается

установите [NodeJS](https://nodejs.org/en/)
установите глобально:
[Yarn](https://yarnpkg.com/getting-started): npm i -g yarn
[Gulp](https://gulpjs.com/): npm i -g gulp
[Bem Tools](https://www.npmjs.com/package/bem-tools-core): npm i -g bem-tools-core
скачайте сборку с помощью [Git](https://git-scm.com/downloads): git clone https://github.com/andreyalexeich/gulp-scss-starter.git
перейдите в скачанную папку со сборкой: cd gulp-scss-starter
введите yarn set version berry
скачайте необходимые зависимости: yarn

**Comment by zagz16** [comment]
урааа победил. просто сначала клонировать репозиторий, потом войти в папку, далее делать 
[Yarn](https://yarnpkg.com/getting-started): npm i -g yarn
[Gulp](https://gulpjs.com/): npm i -g gulp
[Bem Tools](https://www.npmjs.com/package/bem-tools-core): npm i -g bem-tools-core
введите yarn set version berry
скачайте необходимые зависимости: yarn install


после этого работает
