### ISSUE TITLE
Структура blocks

### ISSUE THREAD

**Issue by XIOLog** [andreyalexeich/gulp-scss-starter#46]
Андрей, добрый день. Ваша сборка мне очень нравится, но есть вопрос по bem в директории blocks. Для main.html есть примеры использования. Подскажите, пожалуйста, как должен выглядеть файл main.js? Хотя бы небольшой пример.

**Comment by andreyalexeich** [comment]
Привет! В ```index.js``` импортируется ```blocks.js```, в который в свою очередь импортируются скрипты БЭМ-блоков (например, код слайдера для секции). На выходе получается просто скомпонованный js-файл, по аналогии  c scss-файлом с ```@import```

**Comment by XIOLog** [comment]
Я думал, что там прописывается js-код для создания структуры bem :-) Понял. Спасибо
