### ISSUE TITLE
Скролл страниц

### ISSUE THREAD

**Issue by ArutaGerman** [andreyalexeich/gulp-scss-starter#50]
Добрый день! 

Начал использовать сборку - вроде разобрался. НО не сроллятся страницы при верстке.
Верстку делаю по блокам - header, main, footer.
В index.html вставлены все блоки через rigger: //= ..........
Сверстал header(со стилями), main(html только), но при просмотре в браузере невозможно пролистать страницу вниз, чтобы увидеть остальные элементы. Только, если масштабом баловаться. 
С уменьшенным масштабом - http://prntscr.com/ncjxgi
100% масштаб -   http://prntscr.com/ncjysk

P.s. проверял даже если код писать полностью в index.html (в папке view) - всё равно не скроллится.

Я что-то не так делаю?
Если это баг, то как его исправить?

**Comment by ArutaGerman** [comment]
> Добрый день!
> 
> Начал использовать сборку - вроде разобрался. НО не сроллятся страницы при верстке.
> Верстку делаю по блокам - header, main, footer.
> В index.html вставлены все блоки через rigger: //= ..........
> Сверстал header(со стилями), main(html только), но при просмотре в браузере невозможно пролистать страницу вниз, чтобы увидеть остальные элементы. Только, если масштабом баловаться.
> С уменьшенным масштабом - http://prntscr.com/ncjxgi
> 100% масштаб - http://prntscr.com/ncjysk
> 
> P.s. проверял даже если код писать полностью в index.html (в папке view) - всё равно не скроллится.
> 
> Я что-то не так делаю?
> Если это баг, то как его исправить?

Нашел, только не понятно - для чего position: fixed в базовой сборке добавлено?:)

**Comment by andreyalexeich** [comment]
> Нашел, только не понятно - для чего position: fixed в базовой сборке добавлено?:)

Потому что я верстал заглушку :)) Её удалить надо было
