### ISSUE TITLE
Imagemin

### ISSUE THREAD

**Issue by ArutaGerman** [andreyalexeich/gulp-scss-starter#53]
Снова я:)
Заметил такую штуку:
Дома использую Win 7 - imagemin работает отлично.
На работе Win10 стоит и при попытке png-24 картинок сжать выдаёт ошибку, что качество не установлено и должно быть  0-100:  
![image](https://user-images.githubusercontent.com/48782221/56707579-0b85bc00-674c-11e9-9abb-3b6f6b61b5e4.png)

Почему на Win10 ругается, а на win7 нет?

**Comment by andreyalexeich** [comment]
@ArutaGerman попробуй переустановить node_modules, плагин обновлялся

**Comment by ArutaGerman** [comment]
уже несколько раз делал это - проблема только на win 10 сохраняется. + еще и ругается часто вот на что: pngquant-bin и просит поставить его расширение, которое ставится только на linux

уже кучу инфы перекопал и не нашел ответ, как работать на актуальной версии без ошибки - приходится удалять png из папки, без них билдить и потом снова в папку вкидывать, что в src что в  dist

**Comment by andreyalexeich** [comment]
Странно, что у других работает на 10-ке...
