### ISSUE TITLE
Не подтягиваются картинки и CSS

### ISSUE THREAD

**Issue by uCryNet** [andreyalexeich/gulp-scss-starter#77]
1) У вас в /src/views/index.html в файле прописано: `<link rel="stylesheet" href="../styles/main.css">`
Если так оставить, то index.html не найдёт стили, необходимо вышеуказанную строку заменить на `<link rel="stylesheet" href="styles/main.css">` и все заработает
2) При разработке и создания билда в папку dist/img не копируются картинки включая папку svg, которая есть в src/img по умолчанию, только favicons. Как исправить?

**Comment by andreyalexeich** [comment]
@uCryNet пути указаны правильно, на локалке они и не должны работать - только на хостинге и по browsersync. С картинками всё хорошо, недавно проектик закончил. Давай подробнее

**Comment by uCryNet** [comment]
> на локалке они и не должны работать - только на хостинге
А в чём разница? :) Хочу на на своей машине запустить. Проверить и т.д.
______________
ОК. Тогда с самого начала :) Как правильно указывать путь к картинкам в HTML, чтобы работал шаблон и локально, и на хостинге?
```
<img src="img/unit.webp" alt="image">
<img src="/img/unit.webp" alt="image">
<img src="../img/unit.webp" alt="image">
```

**Comment by andreyalexeich** [comment]
> > на локалке они и не должны работать - только на хостинге
> 
> А в чём разница? :) Хочу на на своей машине запустить. Проверить и т.д.
> 
> ОК. Тогда с самого начала :) Как правильно указывать путь к картинкам в HTML, чтобы работал шаблон и локально, и на хостинге?
> 
> ```
> <img src="img/unit.webp" alt="image">
> <img src="/img/unit.webp" alt="image">
> <img src="../img/unit.webp" alt="image">
> ```

я всегда пишу `../`
