### ISSUE TITLE
Библиотеки CDN дописывает .min (bootstrap.min.min.css)

### ISSUE THREAD

**Issue by Timur-Kharkov** [andreyalexeich/gulp-scss-starter#86]
Добрый день!
При подключении библиотеки CDN дописывает (.min) при сборке проекта.
И получается такое вот (bootstrap.min.min.css).
В результате не находит ссылку.
С .js то же самое.

И никак не могу подключить jquery"
через import $ from "jquery";
пишет "not found"
с "wowjs" так же.

Помогите, пожалуйста.

**Comment by andreyalexeich** [comment]
@Timur-Kharkov если подключать что-то по CDN, дополнительный .min придётся удалять, потому что добавление этого префикса указано для сборки в продакшн-режиме. А по поводу jQuery, покажи скриншоты и консоль

**Comment by andreyalexeich** [comment]
Проблему решили в чате

**Comment by rasxod** [comment]
А сюда небыло смысла решения написать?
