### ISSUE TITLE
Incorrect source maps when using Gulp with source maps plugin

### ISSUE THREAD

**Issue by Maksiemens** [andreyalexeich/gulp-scss-starter#89]
The weird issue is that having  gulp-group-css-media-queries, is causing this issue. This is bug and currently I am able to fix is by temporarily removing gulp-group-css-media-queries plugin.

**Comment by andreyalexeich** [comment]
@Maksiemens привет, проблему решил?

**Comment by Maksiemens** [comment]
Привет, да, переделал сборку под себя

вт, 10 дек. 2019 г. в 17:28, Andrey Gorokhov <notifications@github.com>:
