### ISSUE TITLE
Как правильно подключить библиотеки?

### ISSUE THREAD

**Issue by VasilyKonnov** [andreyalexeich/gulp-scss-starter#93]
Мне нужно подключить несколько библиотек у них файлы .css и .js 
Есть примеры более подробные, с jquery то, что из описания, не прокатило.

**Comment by andreyalexeich** [comment]
_Разобрались в чате ТВ_

**Comment by vlad320** [comment]
@andreyalexeich Добрый день. Присоединяюсь к вопросу, у меня тоже не выходит :/
npm i jquery

после этого как в js блока появляется import $ from "jquery"; весь js прекращает свою работу, ошибок нет, console.log тоже пропадают. Закоментировав import $ from "jquery"; в консоле сразу вылупляются консоль логи, так что js подключается. В main.js также не наблюдаю jquery библиотеку

**Comment by manunited9393** [comment]
Может подсказать мне ответ? спасибо

**Comment by andreyalexeich** [comment]
@manunited9393 @vlad320  надо бы посмотреть по тимвиверу, например

**Comment by manunited9393** [comment]
я относительно beginner, вот узнал про сборку влез, нравится, но со скриптами совсем беда, видно очень много пробелом в изучении, рано залез, но все же, пользуясь этой сборкой, до скриптов все было удобно, везде примеры были четкие, хочу owlcarousel загрузить, создал папку carousel в node_modules, туда заикнул необходимые 3 файла (2 css и один js) оттуда уже подключил css в lib как было сказанно, а вот js не могу понять как подключить вот это пример не очень понятен import $ from "jquery";

**Comment by andreyalexeich** [comment]
> создал папку carousel в node_modules, туда заикнул необходимые 3 файла (2 css и один js) оттуда уже подключил css в lib как было сказанно

там сказано скачивать библиотеки через ```yarn add```, но owl не работает на сборщиках, советую swiper

**Comment by vlad320** [comment]
@manunited9393 @andreyalexeich Добрый день, у меня вышло самому разобраться.
Кстати, на счет owl, он ставится через npm i/yarn add - вторая версия. Его я первым поставил на этой сборке.

https://www.npmjs.com/package/owl.carousel2
npm i owl.carousel2

До этого:
1) npm i jquery (хотя он вроде из коробки был)
2) webpack.config.js 
Там добавить
var webpack = require('webpack');

`plugins: [
        new webpack.ProvidePlugin({
            'jQuery': 'jquery',
            'window.jQuery': 'jquery',
            'jquery': 'jquery',
            'window.jquery': 'jquery',
            '$': 'jquery',
            'window.$': 'jquery'
        })
    ],`

![image](https://user-images.githubusercontent.com/16899697/71542200-08179400-29af-11ea-83d6-ccfed03e2173.png)


3) В нужном блоке подключить в js jquery и слайдер
![image](https://user-images.githubusercontent.com/16899697/71542214-2aa9ad00-29af-11ea-887f-38b268f9b86c.png)

4) Добавить css слайдера из установленного пакета в файл src/styles/vendor/_libs.scss

@import "../../../node_modules/owl.carousel2/dist/assets/owl.carousel";

![image](https://user-images.githubusercontent.com/16899697/71542230-65134a00-29af-11ea-80e3-9981aac61dde.png)


5) Наслаждаться жизнью

@andreyalexeich спасибо за чудесную сборку, но емае, инструкцию нужно доработать:) 
Я Back-end щик вообще, версткой занимался 4-5 лет назад, тогда еще без сборщиков. Тут прилетел личный проект и я пощел искать готовый. Пока разобрался с плагинами, 4 часа прошло ей богу.

Например, без второго пункта ни один плагин изначально не видит jquery, а четвертый вообще интуитивно чудом догадался, находил примеры в других сборках, но никак не мог путь угадать+sass то оказывается требуется без .css файлы подключать. P.s да, конечно верстай я, я бы знал об этом. Но думаю многие новички будут брать вашу сборку без знания sass на первом этапе, им бы пригодился полный  пример подключения 1 библиотеки.

С наступающим Новым годом!

**Comment by andreyalexeich** [comment]
@vlad320 jQuery раньше подключался без этих манипуляций... Странно

**Comment by manunited9393** [comment]
sorry, может могу я с кем пообщаться в более удобном месте по поводу использования в js? спасибо, знаю что слишком слаб в этом, хорошо бы кто-то мог помочь, спасибо

**Comment by manunited9393** [comment]
установил swiper как сказано через строку, добавил файлы, выдает ошибку
![Снимок](https://user-images.githubusercontent.com/56319570/71547144-0cdb4880-29ad-11ea-80ab-0379d0570e1b.PNG)
![Снимок1](https://user-images.githubusercontent.com/56319570/71547145-0cdb4880-29ad-11ea-9a99-c5defa09bd44.PNG)

**Comment by manunited9393** [comment]
еще проблемка в src гланый js называется index.js и в index.html подключается index.js , а уже в dist гланвый js называется main.js в то время когда index.html просит именно index.js т.е. вообще скрипты не работают пока я main ручную не переименую в index.js но это естественно до первого обновления, и файл превращается обратно вт main.js и рнричего не работает, сорян если слишком тупые проблемы спасибо за ответы

**Comment by andreyalexeich** [comment]
> когда index.html просит именно index.js т.е. вообще скрипты не работают пока я main ручную не переименую в index.js но это естественно до первого обновления, и файл превращается обратно вт main.js и рнричего не работает

В этой строке попробуй вместо ```index.js``` указать ```main.js```, поможет ли? У ребят таких проблем не было

**Comment by manunited9393** [comment]
![Снимок](https://user-images.githubusercontent.com/56319570/71548598-f8557b00-29c1-11ea-993b-c98f302add4d.PNG)
![Снимок1](https://user-images.githubusercontent.com/56319570/71548599-f8557b00-29c1-11ea-9856-0f7e9e2f43f4.PNG)
а где проблема в коде? все сделал по твоему методу, подключил swiper через командную строку, добавил все как сказал вроде начинаю догонять, но результат не меняется))

**Comment by andreyalexeich** [comment]
> а где проблема в коде?
подключение правильное, а там не знаю)

**Comment by manunited9393** [comment]
сейчас вроде как все настроил, разобрался, но нет уверенности что в следующий раз с легкостью так смогу, хотел спросить по поводу jquery очень много плагинов требуют jquery, я так понимаю его сразу нужно подключить для будующих целей и вписать в config вот это верно я понимаю? что бы использовать послеющие плагины на jquery
var webpack = require('webpack');
plugins: [ new webpack.ProvidePlugin({ 'jQuery': 'jquery', 'window.jQuery': 'jquery', 'jquery': 'jquery', 'window.jquery': 'jquery', '$': 'jquery', 'window.$': 'jquery' }) ],

еще по воду bootstrap, я так понимаю он подключен? все что с ним связанно я могу использовать без проблем? (еще не дошел, заранее вопрос) спасибо большое за ответы

и еще сбой не большое в верствке на выходе в dist index.html 
![Снимок](https://user-images.githubusercontent.com/56319570/71561345-619ec200-2a86-11ea-9c1a-444e935e44f7.PNG)
![Снимок1](https://user-images.githubusercontent.com/56319570/71561346-619ec200-2a86-11ea-8220-7c431d1184dc.PNG)

спасибо большое за помощь, если сильные затупы, объясни пожалуйста, очень помогает в понимании

**Comment by andreyalexeich** [comment]
> var webpack = require('webpack');
plugins: [ new webpack.ProvidePlugin({ 'jQuery': 'jquery', 'window.jQuery': 'jquery', 'jquery': 'jquery', 'window.jquery': 'jquery', '$': 'jquery', 'window.$': 'jquery' }) ]

уже добавил

**Comment by manunited9393** [comment]
спасибо) еще вопросы были
